### PR TITLE
Upgraded Project and Unity Standard  Assets.

### PR DESCRIPTION
**Pull request by IsaiahKelly**
Upgraded Project to Unity 5.5.2f1. Updated Unity Standard  Assets. Fixed obsolete code warnings. Remove strange missing Glow components from Afterburner GameObjects?

### CODE REVIEW

**Comment by IsaiahKelly** [comment]
Merged Master fork changes into Develop fork.

**Comment by IsaiahKelly** [comment]
Oops! Didn't mean to make a a pull request for the original project just yet. I was actually just trying to update my own fork. My bad. Please ignore this.

**Comment by VirtualMaestro** [comment]
What about updating to Unity 5.6 and version of entitas 0.40 ?

**Comment by IsaiahKelly** [comment]
@VirtualMaestro That is actually my plan, but upgrading Entitas is no easy task, at least for me anyway. Just preparing the project for further upgrades at the moment and this was a premature accidental pull request. I'll submit another pull request when/if I get Entitas upgraded to the latest version. Fingers crossed!

**Comment by VirtualMaestro** [comment]
@IsaiahKelly I see) Thank you.

**Pull request closed without merging**
